### ISSUE TITLE
Undocumented things

### ISSUE THREAD

**Issue by ASDownloadingAccount** [Proton0/fbutil#1]
I don't know what to do if I want to remove the picture or change it

**Comment by Proton0** [comment]
You can remove the picture from the screen by touching the screen or swiping but you need to stop the `dd` or `cat` command by ctrl+c or exiting the shell

If you want to stop surface update then use [stop_surface_update.sh](https://github.com/Proton0/fbutil/blob/main/util/disable_surface_update.sh) or by going to developer options and turning off the option there

or simply reboot

**Comment by ASDownloadingAccount** [comment]
> You can remove the picture from the screen by touching the screen or swiping but you need to stop the `dd` or `cat` command by ctrl+c or exiting the shell
> 
> If you want to stop surface update then use [stop_surface_update.sh](https://github.com/Proton0/fbutil/blob/main/util/disable_surface_update.sh) or by going to developer options and turning off the option there
> 
> or simply reboot

How can I change it? That's the next question

**Comment by Proton0** [comment]
> How can I change it? That's the next question

You can re-run the generate framebuffer command and push it to your device and run dd to see it
